---
--- Generated by Luanalysis
--- Created by CHEN.
--- DateTime: 2022/10/12 17:37
---

---秒杀券id
local voucherId = ARGV[1]
--用户id
local userId = ARGV[2]
--订单id
local id = ARGV[3]

--库存key
local stockKey = 'seckill:stock:' .. voucherId
--订单key
local orderKey = 'seckill:order:' .. voucherId

--获取库存
local stock = redis.call('get', stockKey)
--库存不存在或库存不足
if (not stock or tonumber(stock) <= 0) then
    return 1
end

--判断用户是否下单
--存在用户 禁止重复下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end

--扣减库存
redis.call('incrby',stockKey,-1)
--下单（保存用户）
redis.call('sadd',orderKey,userId)
--发送消息
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',id)
return 0

